version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 891377322463.dkr.ecr.us-west-2.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t my-docker-image .
      - docker tag my-docker-image:latest 891377322463.dkr.ecr.us-west-2.amazonaws.com/my-docker-image:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 891377322463.dkr.ecr.us-west-2.amazonaws.com/my-docker-image:latest
      - echo Writing image definitions file...
      - printf '[{"name":"my-web-server","imageUri":"%s"}]' 891377322463.dkr.ecr.us-west-2.amazonaws.com/my-docker-image:latest > imagedefinitions.json
artifacts:
  files: 
      - imagedefinitions.json
      - appspec.yml
